### ISSUE TITLE
Two clients may have the same username

### ISSUE THREAD

**Issue by poifra** [Dagothig/node-bang#19]

**Comment by Dagothig** [comment]
Just need to check, were they reported as two different people by the server, or both had the same identity? If they both had the same identity, then that is in fact working as intended.

**Comment by poifra** [comment]
They appeared as one user. This however allows anyone to take control of someone else's game, as they don't need the same password to login as the same user.

**Comment by Dagothig** [comment]
Are you able to reproduce it? and by reproducing I mean logging as the same person using two different passwords. Right now as it is supposed to be working (and as far as my testing as shown), then to be connected twice as the same person, you need to provide the same password. In fact, this is the sole reason why you need a password in the first place.

**Comment by poifra** [comment]
Maybe we had the same password by accident, it works as you describe. However, what is the thought process behind allowing multiple clients for someone?

**Comment by Dagothig** [comment]
Ease of switching between computers mostly; if it is setup with a decent timeout length (say, a minute), then switching between computers would require waiting a minute for the old client to be out. Otherwise, it could also disconnect the other sockets, but that feels unnecessary (and is a tad annoying, depending on who you ask).
In the end it is a relatively arbitrary decision; I am open to arguments for other systems.
